@echo off
echo Creating Voting System Deployment Package...

REM Create deployment directory
if exist "VotingSystem_Deployment" rmdir /s /q "VotingSystem_Deployment"
mkdir "VotingSystem_Deployment"

REM Copy essential files
copy "vote_standalone.exe" "VotingSystem_Deployment\vote.exe"
copy "README.md" "VotingSystem_Deployment\"
copy "personinfo_sample.txt" "VotingSystem_Deployment\personinfo.txt"

REM Create empty result files (will be generated by the program)
echo. > "VotingSystem_Deployment\current_winner.txt"
echo. > "VotingSystem_Deployment\results.txt"
echo. > "VotingSystem_Deployment\voted.txt"

echo.
echo Deployment package created in "VotingSystem_Deployment" folder!
echo.
echo Files included:
echo - vote.exe (main voting application)
echo - README.md (user instructions)
echo - personinfo.txt (sample voter credentials)
echo - current_winner.txt (election results - auto-generated)
echo - results.txt (detailed data - auto-generated)
echo - voted.txt (vote tracking - auto-generated)
echo.
echo Ready to share! The recipient only needs to:
echo 1. Extract all files to a folder
echo 2. Update personinfo.txt with real voter credentials
echo 3. Run vote.exe
echo.
pause
